import Head from 'next/head'
import Landing from './frontend/Landing'
import { getCategoriesData  , getProductsData } from '@/services/admin';



export async function getStaticProps() {

  const category = await getCategoriesData() || [];
  const totalProduct = await getProductsData() || [];

  const product = totalProduct.slice(0, 8)


  return {
    props: { category, product }
  }

}

export default function Home({category , product}) {
  return (
    <>
      <Head>
        <title>E-commerce APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing category={category} product={product} />
    </>
  )
}




